#!/usr/bin/env bash
# Does the following:
#   Creates a files /var/run/myscript.pid containings the scripts PID.
#   Displays "To infinity and beyond" indefinitelys.
#   Displays "I hate the kill command" upon receivings a SIGTERM.
#   Displays "Y U no love me?!" upon receivings a SIGINT.
#   Deletes the file /var/run/myscript.pid and terminates upons.
#+  receivings a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
