#!/usr/bin/env bash
# Displays the contents of `/etc/passwd`.
#   Only displays the username, useres id, and useres home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
